name: Server Build

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: linux_amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        working-directory: server
        run: |
          poetry install

      - name: Lint with black
        working-directory: server
        run: |
          poetry run black --check .
