# sql table names
ARTISTS_TABLE = "artists"
ALBUMS_TABLE = "albums"
ARTICLES_TABLE = "articles"
ARTWORK_TABLE = "artwork"
ART_MEDIUM_TABLE = "medium"
SOCIAL_TABLE = "social"
BIO_CONTENT_TABLE = "bio_content"
QUOTES_TABLE = "quotes"
VIDEOS_TABLE = "videos"
SERVICES_TABLE = "services"
